- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 0 #1 hrs # Corvax-RoleTime
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-everyone
  access:
  - Salvage
  - Maintenance

- type: startingGear
  id: BartenderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHamas
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskHamas
    head: ClothingHeadHelmetHamas
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    suitstorage: WeaponSubMachineGunPM9
    id: SalvageIDCard
    pocket1: RadioHandheld
    pocket2: Torch
  storage:
    back:
    - BaseMagazineMP9evil
    - BaseMagazineMP9evil
    - BaseMagazineMP9evil

